name: Bundle

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  bundle:
    uses: ElevatedSensors/bed-presence-mk1/.github/workflows/hubitat-bundle.yml@main
    with:
      product-name: "bed-presence-mk1"
      build-type: "nightly"
